#!/bin/bash
# SETUP.sh
# generated by Claude
set -e

echo "=========================================="
echo "OpenVault - Dependency Setup"
echo "=========================================="
echo ""

# Detect operating system
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    echo "Detected: Linux"
    echo "Installing OpenSSL development libraries..."
    
    # Check if apt is available (Debian/Ubuntu)
    if command -v apt-get &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y libssl-dev
        echo "✓ OpenSSL installed successfully"
    
    # Check if yum is available (RedHat/CentOS/Fedora)
    elif command -v yum &> /dev/null; then
        sudo yum install -y openssl-devel
        echo "✓ OpenSSL installed successfully"
    
    # Check if pacman is available (Arch Linux)
    elif command -v pacman &> /dev/null; then
        sudo pacman -S --noconfirm openssl
        echo "✓ OpenSSL installed successfully"
    
    else
        echo "✗ Could not detect package manager"
        echo "Please install OpenSSL development libraries manually"
        exit 1
    fi

elif [[ "$OSTYPE" == "darwin"* ]]; then
    echo "Detected: macOS"
    
    # Check if Homebrew is installed
    if command -v brew &> /dev/null; then
        echo "Installing OpenSSL via Homebrew..."
        brew install openssl
        echo "✓ OpenSSL installed successfully"
        echo ""
        echo "Note: OpenSSL location on macOS:"
        echo "  $(brew --prefix openssl)"
        echo ""
        echo "The Makefile will automatically use this location."
    else
        echo "✗ Homebrew not found"
        echo "Please install Homebrew first: https://brew.sh"
        echo "Then run this script again"
        exit 1
    fi

elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    echo "Detected: Windows (Git Bash/MSYS/Cygwin)"
    echo ""
    echo "For Windows, please install OpenSSL manually:"
    echo "  1. Install MSYS2 from https://www.msys2.org/"
    echo "  2. Open MSYS2 terminal and run:"
    echo "     pacman -S mingw-w64-x86_64-openssl"
    echo ""
    echo "Or use WSL (Windows Subsystem for Linux) for easier setup"
    exit 1

else
    echo "✗ Unknown operating system: $OSTYPE"
    echo "Please install OpenSSL development libraries manually"
    exit 1
fi

echo ""
echo "=========================================="
echo "Verifying OpenSSL installation..."
echo "=========================================="

# Verify OpenSSL is installed
if command -v openssl &> /dev/null; then
    echo "✓ OpenSSL command-line tool found"
    openssl version
else
    echo "✗ OpenSSL command-line tool not found"
    echo "Installation may have failed"
    exit 1
fi

echo ""
echo "=========================================="
echo "Setup Complete!"
echo "=========================================="
echo ""
echo "You can now build OpenVault:"
echo "  make clean"
echo "  make exe_dbg"
echo "  ./bin/main_dbg"
echo ""